train:
    # optimizer
    learning_rate: 0.0001
    max_grad_norm: 5

    # a3c
    agents_n: 4
    update_agent_frequency: 20

    # loss
    gamma: 0.99 # train discount coef
    tau: 1.00 # GAE parameter
    value_weight: 0.5
    entropy_weight: 0.01

    # environment
    env_name: "SpaceInvaders-v0"

environment:
    # Nope... :(
